services:
  # Backend Web Service  
  - type: web
    name: risk-radar-backend
    rootDir: backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "10000"
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: risk-radar-frontend  
    env: node
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
    pullRequestPreviewsEnabled: true