services:
  # Frontend Static Site
  - type: static
    name: risk-radar-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: risk-radar-backend
          property: host
    pullRequestPreviewsEnabled: true

  # Backend Web Service  
  - type: web
    name: risk-radar-backend
    rootDir: backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "10000"
    healthCheckPath: /health